import { Nav as Navbar } from "@/components/navbar";
import { MobileNav } from "@/components/mobileNav";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Divider } from "antd";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="mt-5">
          <Navbar />
          <Divider className="border-l-neutral-950"/>
          {children}
          <MobileNav />
        </div>
      </body>
    </html>
  );
}
